
services:
  app:
    container_name: sql-ai-app
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ..:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    env_file: app/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: sql-ai-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  node_modules:
  db_data:
